-- MySQL Script generated by MySQL Workbench
-- Wed Aug 14 12:40:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eastar-renewal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eastar-renewal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eastar-renewal` DEFAULT CHARACTER SET utf8 ;
USE `eastar-renewal` ;

-- -----------------------------------------------------
-- Table `eastar-renewal`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eastar-renewal`.`User` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `firebaseUID` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  `birth` DATE NOT NULL,
  `phoneNumber` VARCHAR(15) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  UNIQUE INDEX `firebaseUID_UNIQUE` (`firebaseUID` ASC),
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phoneNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eastar-renewal`.`Aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eastar-renewal`.`Aircraft` (
  `aircraftId` VARCHAR(20) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `totalSeatsEconomy` INT UNSIGNED NOT NULL,
  `totalSeatsBuisness` INT UNSIGNED NOT NULL,
  `totalSeatsFirst` INT UNSIGNED NOT NULL,
  `maxTakeoffWeight` INT UNSIGNED NOT NULL,
  `maxFuelCapacity` INT UNSIGNED NOT NULL,
  `maxRange` INT UNSIGNED NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`aircraftId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eastar-renewal`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eastar-renewal`.`Flight` (
  `flightId` VARCHAR(20) NOT NULL,
  `aircraftId` VARCHAR(20) NOT NULL,
  `airlineCode` VARCHAR(3) NOT NULL DEFAULT 'ZE',
  `flightNumber` VARCHAR(10) NULL,
  `departureAirport` VARCHAR(5) NULL,
  `arrivalAirport` VARCHAR(5) NULL,
  `departureTime` DATETIME NULL,
  `arrivalTime` DATETIME NULL,
  `status` ENUM('Scheduled', 'Delayed', 'Arrived', 'Cancelled') NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`flightId`, `aircraftId`),
  UNIQUE INDEX `flightId_UNIQUE` (`flightId` ASC),
  INDEX `idx_departure` (`departureAirport` ASC, `departureTime` ASC),
  INDEX `idx_arrival` (`arrivalAirport` ASC, `arrivalTime` ASC),
  INDEX `aircraftId_idx` (`aircraftId` ASC),
  CONSTRAINT `aircraftId`
    FOREIGN KEY (`aircraftId`)
    REFERENCES `eastar-renewal`.`Aircraft` (`aircraftId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eastar-renewal`.`FlightPrice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eastar-renewal`.`FlightPrice` (
  `priceId` INT NOT NULL AUTO_INCREMENT,
  `flightId` VARCHAR(20) NOT NULL,
  `classType` ENUM('basic', 'standard', 'premium') NOT NULL,
  `basePrice` INT UNSIGNED NOT NULL,
  `availableSeats` INT UNSIGNED NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`priceId`),
  INDEX `flightId_idx` (`flightId` ASC),
  UNIQUE INDEX `unique_flight_class` (`flightId` ASC, `classType` ASC),
  CONSTRAINT `flightId`
    FOREIGN KEY (`flightId`)
    REFERENCES `eastar-renewal`.`Flight` (`flightId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
